"""empty message

Revision ID: cb193a49c433
Revises: 0
Create Date: 2020-12-03 14:09:25.597450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cb193a49c433"
down_revision = "0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(), nullable=True),
        sa.Column("complete", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    op.create_table(
        "problem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("domain", sa.VARCHAR(length=4), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id"),
    )
    op.create_table(
        "formula",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("json", sa.JSON(), nullable=True),
        sa.Column("problem_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["problem_id"], ["problem.id"]),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "problem_imports",
        sa.Column("problem_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["problem_id"], ["problem.id"]),
        sa.ForeignKeyConstraint(["source_id"], ["source.id"]),
    )
    op.create_table(
        "solution",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("problem_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["problem_id"], ["problem.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "association",
        sa.Column("left_id", sa.Integer(), nullable=False),
        sa.Column("right_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["left_id"], ["problem.id"]),
        sa.ForeignKeyConstraint(["right_id"], ["formula.id"]),
    )
    op.create_table(
        "solution_premises",
        sa.Column("solution_id", sa.Integer(), nullable=False),
        sa.Column("formula_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["formula_id"], ["formula.id"]),
        sa.ForeignKeyConstraint(["solution_id"], ["solution.id"]),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("solution_premises")
    op.drop_table("association")
    op.drop_table("solution")
    op.drop_table("problem_imports")
    op.drop_table("formula")
    op.drop_table("problem")
    op.drop_table("source")
    # ### end Alembic commands ###
