"""Only one problem per conjecture

Revision ID: b07c666fda22
Revises: 31dea3c34326
Create Date: 2020-11-18 14:25:40.531002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b07c666fda22"
down_revision = "31dea3c34326"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "conjecture_source", "problem", ["source_id", "conjecture_id"]
    )
    op.drop_column("problem", "name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "problem",
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    op.drop_constraint("conjecture_source", "problem", type_="unique")
    # ### end Alembic commands ###
