"""empty message

Revision ID: 031ea43d82c2
Revises: cb193a49c433
Create Date: 2020-12-30 15:28:38.543295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031ea43d82c2'
down_revision = 'cb193a49c433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solution', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solution', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
